spring.application.name=DigitaliTechnicalChallengeTest

#properties para la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useUnicode=true& \
characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=qwer

spring.datasource.platform=postgres

#toma por defecto este eschema para no tener que definirlo en cada entity manualmente
spring.jpa.properties.hibernate.default_schema=digitali
